export const adminPaths = {
  dashboard: "/admin/dashboard",
  pos: "/admin/pos",
  classes: "/admin/classes",
  workout: "/admin/workout",
  members: "/admin/members",
  invoices: "/admin/invoices",
  membershipPlans: "/admin/membership-plans",
  reports: "/admin/reports",
  coachRates: "/admin/coach-rates",
  payroll: "/admin/payroll",
  agreements: "/admin/agreements",
  payments: "/admin/payments",
  paymentMethods: "/admin/payment-methods",
  users: "/admin/users",
  history: "/admin/history",
  pt: "/admin/pt",
  scan: "/admin/scan",
  scanCamera: "/admin/scan-camera",
  settings: "/admin/settings",
  systemSettings: "/admin/system-settings",
  dropIn: "/admin/drop-in",
  promoBanners: "/admin/promo-banners",
  help: "/admin/help",
} as const;

export type AdminNavKey = keyof typeof adminPaths;

export const pageTitleByPath: Record<string, string> = {
  [adminPaths.dashboard]: "Dashboard Overview",
  [adminPaths.pos]: "Front Desk POS",
  [adminPaths.classes]: "Class Schedule",
  [adminPaths.workout]: "Workout Management",
  [adminPaths.members]: "Membership",
  [adminPaths.invoices]: "Payments & Invoices",
  [adminPaths.membershipPlans]: "Membership Plans",
  [adminPaths.reports]: "Attendance Reports",
  [adminPaths.coachRates]: "Coach Rates",
  [adminPaths.payroll]: "Coaches Payroll",
  [adminPaths.agreements]: "Agreement Documents",
  [adminPaths.payments]: "Payments",
  [adminPaths.paymentMethods]: "Payment Method",
  [adminPaths.users]: "User Management",
  [adminPaths.history]: "History",
  [adminPaths.pt]: "Personal Training",
  [adminPaths.scan]: "Barcode Scanner",
  [adminPaths.scanCamera]: "Webcam Scanner",
  [adminPaths.settings]: "Brand Settings",
  [adminPaths.systemSettings]: "System Settings",
  [adminPaths.dropIn]: "Drop In",
  [adminPaths.promoBanners]: "Promo Banners",
  [adminPaths.help]: "Help & Support",
};
